# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'

target 'AwesomeNavigation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'React', :path=> '../node_modules/react-native', :subspecs => [
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTNetwork',
    'RCTImage',
    'RCTWebSocket', # needed for debugging
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # Pods for AwesomeNavigation

  # target 'AwesomeNavigation-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'AwesomeNavigationTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'AwesomeNavigation-tvOS' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for AwesomeNavigation-tvOS

#   target 'AwesomeNavigation-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
